name: Testes Python do Programa StringChanger (CI)

# gatilhos
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # executa o job uma vez para cada combinação de OS e versão de Python.
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    # define o os para a execução atual do job
    runs-on: ${{ matrix.os }}

    steps:
      # baixar o código do repo para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # configurar a versão do Python (puxando da matrix)
      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # instalar as dependências do projeto
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # rodar os testes
      - name: Rodar testes com pytest
        run: |
          pytest